name: Maven Release

on:
  push:
    branches: [ master ]


jobs:
  release:
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[ci skip]') || !contains(github.event.head_commit.message, '[skip ci]'))

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Release with Maven
        uses: qcastel/github-actions-maven-release@v1.12.5
        with:
          #          https://github.com/qcastel/github-actions-maven-release
          release-branch-name: "master"
          version-minor: true
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@github.com"
          access-token: ${{ secrets.GITHUB_TOKEN }}
      #          skip-perform: true


      #      - name: Cache Maven packages
      #        uses: actions/cache@v2
      #        with:
      #          path: ~/.m2
      #          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #          restore-keys: ${{ runner.os }}-m2
#      - name: Maven Release Clean
#        run: ./mvnw -B clean release:clean
#      - name: Release with Maven
#        uses: qcastel/github-actions-maven-release@v1.12.5
#        with:
#          release-branch-name: "master"
#          version-minor: true
#          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
#          git-release-bot-name: "release-bot"
#          git-release-bot-email: "release-bot@github.com"
#          access-token: ${{ secrets.GITHUB_TOKEN }}
##          skip-perform: false
